config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/healthz' => 'health#index'
  get '/error' => 'error#index', as: 'error'

  # set redirector root to /invitations/books
  root to: redirect('/invitations/books')

  # modify devise path_names to avoid clash with existing
  devise_for :users, path: '_auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  namespace :admin, path: '_adminz' do

    # home controller, only display index and error. no resources
    get '/' => 'home#index', as: 'root'
    get '/error' => 'home#error', as: 'error'

    resources :venues
    resources :weddings
    resources :invitations
    resources :guests

    resources :users do
      patch '/confirm' => 'users#confirm', as: 'confirm'
      patch '/revoke' => 'users#revoke', as: 'revoke'
    end
  end

  namespace :invitations do
    scope :books do
      get '/' => 'books#index'
      get '/:id' => 'books#show', as: 'show'

      post '/:id' => 'books#create', as: 'create'
    end
  end
end

app/models/weddings.rb
class Weddings < ApplicationRecord
  self.table_name = "weddings"

  has_many :wedding_venues, class_name: 'WeddingVenue', foreign_key: :wedding_id
  has_many :venues, class_name: 'Venue', through: :wedding_venues

  has_many :invitations, class_name: 'Invitation', foreign_key: :wedding_id
  has_many :invitation_guests, class_name: 'InvitationGuest', through: :invitations
  has_many :guests, class_name: 'Guest', through: :invitation_guests
end

app/controllers/admin/weddings_controller.rb
class Admin::WeddingsController < AdminController
  before_action :load_resource, only: [:update]

  respond_to? :html
  layout 'admin'

  def index
    @weddings = Weddings.all
  rescue StandardError => e
    log_error(e, action_name)
    session[:error_message] = e.message
    session[:error_backtrace] = e.backtrace.take(3)
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_error_url
  end

  def edit
    load_resource
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_weddings_path
  end

  def update
    WeddingService.update(@wedding, update_attributes)

    redirect_to admin_weddings_path, notice: 'Sukses mengubah data perkawinan'
  rescue WeddingService::WeddingError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:warning] = e.message
    redirect_to edit_admin_wedding_path
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to edit_admin_wedding_path
  end

  private

  def load_resource
    @wedding = Weddings.find(params[:id])
  end

  def update_attributes
    params.required(:weddings)
          .permit(:hashtag,
                  :story).to_h
  end
end

app/views/admin/weddings/edit.html.erb
<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-1">
    <a href=<%= admin_weddings_path %> class="no-style-link">
      <span>
        <i class="bx bx-left-arrow-alt"></i>
      </span>
      Back
    </a>
  </div>
  <div class="col-sm-11">
    <h1 class="text-center">Edit Wedding Detail</h1>
  </div>
</div>

<div class="row align-items-center mb-5 mt-5">
  <%= form_with model: @wedding, url: admin_wedding_path(@wedding), method: :patch, local: true do |form| %>
    <div class="form-group">
      <%= form.label :hashtag, "Wedding Hashtag" %>
      <%= form.text_field :hashtag, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :story, "Wedding Story" %>
      <%= form.text_area :story, class: "form-control", rows: 3 %>
    </div>

    <div class="form-group">
      <%= form.submit "Update", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/admin/weddings/index.html.erb
<!-- app/views/admin/weddings/index.html.erb -->

<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <h1 class="text-center">Weddings</h1>
</div>

<div class="row">
  <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>#</th>
        <th>Hashtag</th>
        <th>Holy Matrimony</th>
        <th>Reception</th>
        <th>Groom</th>
        <th>Bride</th>
        <th>Story</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @weddings.each_with_index do |wedding, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= wedding.hashtag %></td>
          <td><%= wedding.venues&.holy_matrimony&.name %></td>
          <td><%= wedding.venues&.reception&.name %></td>
          <td><%= wedding.groom %></td>
          <td><%= wedding.bride %></td>
          <td><%= wedding.story %></td>
          <td>
            <%= link_to 'Edit', edit_admin_wedding_path(wedding), class: 'btn btn-primary' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>