config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/healthz' => 'health#index'
  get '/error' => 'error#index', as: 'error'

  # set redirector root to /invitations/books
  root to: redirect('/invitations/books')

  # modify devise path_names to avoid clash with existing
  devise_for :users, path: '_auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  namespace :admin, path: '_adminz' do

    # home controller, only display index and error. no resources
    get '/' => 'home#index', as: 'root'
    get '/error' => 'home#error', as: 'error'

    resources :venues
    resources :weddings
    resources :invitations
    resources :guests

    resources :users do
      patch '/confirm' => 'users#confirm', as: 'confirm'
      patch '/revoke' => 'users#revoke', as: 'revoke'
    end
  end

  namespace :invitations do
    scope :books do
      get '/' => 'books#index'
      get '/:id' => 'books#show', as: 'show'

      post '/:id' => 'books#create', as: 'create'
    end
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  self.table_name = 'guests'

  GENDER = {
    "0".to_sym => 'female',
    "1".to_sym => 'male'
  }

  CONTACT_SOURCE = {
    "0".to_sym => 'whatsapp',
    "1".to_sym => 'instagram',
    "2".to_sym => 'tiktok'
  }

  def fetch_gender
    GENDER[self.gender.to_s.to_sym]
  end

  def fetch_contact_source
    CONTACT_SOURCE[self.contact_source.to_s.to_sym]
  end

  def fetch_guest_source
    self.from_groom ? "groom" : "bride"
  end

  def fetch_invitation
    self.invitations.first&.id
  end

  has_many :invitation_guests, class_name: 'InvitationGuest', foreign_key: :guest_id
  has_many :invitations, class_name: 'Invitation', through: :invitation_guests
end

app/controllers/admin/guests_controller.rb
class Admin::GuestsController < AdminController
  before_action :load_resource, only: [:update, :destroy]

  respond_to? :html
  layout 'admin'

  def index
    @guests = GuestService.retrieve(index_attributes)
  rescue StandardError => e
    log_error(e, action_name)
    session[:error_message] = e.message
    session[:error_backtrace] = e.backtrace.take(3)
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_error_url
  end

  def new
    @guest = Guest.new
  rescue StandardError => e
    log_error(e, action_name)
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_guests_path
  end

  def create
    GuestService.create(create_attributes)

    redirect_to admin_guests_path, notice: 'Sukses menambah tamu'
  rescue GuestService::GuestError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:warning] = e.message
    redirect_to new_admin_guest_path
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to new_admin_guest_path
  end

  def edit
    load_resource
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_guests_path
  end

  def update
    GuestService.update(@guest, update_attributes)

    redirect_to admin_guests_path, notice: 'Sukses mengubah data tamu'
  rescue GuestService::GuestError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:warning] = e.message
    redirect_to edit_admin_guest_path
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to edit_admin_guest_path
  end

  def destroy
    GuestService.delete(@guest)

    redirect_to admin_guests_path, notice: 'Sukses menghapus tamu'
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_guests_path
  end

  private

  def load_resource
    @guest = Guest.find(params[:id])
  end

  def index_attributes
    attribute = params.permit(:search, :guest_source, :commit).to_h

    # transform attributes
    attribute["search"] = attribute["search"].to_s.strip
    attribute["guest_source"] = attribute["guest_source"].to_s.strip

    attribute
  end

  def create_attributes
    params.required(:guest)
          .permit(:name,
                  :gender,
                  :contact,
                  :contact_source,
                  :from_groom).to_h
  end

  def update_attributes
    params.required(:guest)
          .permit(:name,
                  :gender,
                  :contact,
                  :contact_source,
                  :from_groom).to_h
  end
end

app/views/admin/guests/edit.html.erb
<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-1">
    <a href=<%= admin_guests_path %> class="no-style-link">
      <span>
        <i class="bx bx-left-arrow-alt"></i>
      </span>
      Back
    </a>
  </div>
  <div class="col-sm-11">
    <h1 class="text-center">Edit Guest Detail</h1>
  </div>
</div>

<div class="row align-items-center mb-5 mt-5">
  <%= form_with model: @guest, url: admin_guest_path(@guest), method: :patch, local: true do |form| %>
    <div class="form-group">
      <%= form.label :name, "Guest Name" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :gender, "Guest Gender" %>

      <div class="form-check">
        <%= form.radio_button :gender, 0, class: "form-check-input" %>
        <%= form.label :gender, "Female", value: 1, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :gender, 1, class: "form-check-input" %>
        <%= form.label :gender, "Male", value: 0, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :contact, "Guest Contact" %>
      <%= form.text_field :contact, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :contact_source, "Guest Contact Source" %>
      <%= form.select :contact_source,
                      Guest::CONTACT_SOURCE.keys.map { |key| [Guest::CONTACT_SOURCE[key], key] },
                      { include_blank: "Select Source", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :from_groom, "Guest Relation" %>

      <div class="form-check">
        <%= form.radio_button :from_groom, true, checked: @guest.from_groom == true, class: "form-check-input" %>
        <%= form.label :from_groom, "Groom", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :from_groom, false, checked: @guest.from_groom == false, class: "form-check-input" %>
        <%= form.label :from_groom, "Bride", value: false, class: "form-check-label" %>
      </div>
    </div>
  </div>

    <div class="form-group">
      <%= form.submit "Update", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/admin/guests/index.html.erb
<!-- app/views/admin/guests/index.html.erb -->

<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-11">
    <h1 class="text-center">Guests</h1>
  </div>
  <div class="col-sm-1">
    <%= link_to 'Add', new_admin_guest_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th colspan="8" class="text-center">
          <%= form_tag admin_guests_path, method: :get, class: 'form-inline d-flex justify-content-center' do %>
            <%= text_field_tag :search, params[:search], class: 'form-control mr-2', placeholder: "Search by name", style: "width: 250px;" %>

            <%= select_tag :guest_source,
                options_for_select([['All', ''], ['Groom', 'groom'], ['Bride', 'bride']], params[:guest_source]),
                class: 'form-control mr-2',
                include_blank: false
            %>

            <%= submit_tag 'Search', class: 'btn btn-primary mr-2' %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Contact Info</th>
        <th>Contact Source</th>
        <th>Guest Source</th>
        <th>Invitation</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @guests.each_with_index do |guest, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= guest.name %></td>
          <td><%= guest.fetch_gender %></td>
          <td><%= guest.contact %></td>
          <td><%= guest.fetch_contact_source %></td>
          <td><%= guest.fetch_guest_source %></td>
          <td>
            <% if guest.fetch_invitation.present? %>
              <%= link_to guest.fetch_invitation, invitations_show_path(guest.fetch_invitation) %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_guest_path(guest), class: 'btn btn-primary' %>
            <%= link_to "Delete", admin_guest_path(guest), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
      <tr>
        <<td colspan="8" class="text-center" style="font-weight: bold;">Total Guest: <%= @guests.count %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/guests/new.html.erb
<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-1">
    <a href=<%= admin_guests_path %> class="no-style-link">
      <span>
        <i class="bx bx-left-arrow-alt"></i>
      </span>
      Back
    </a>
  </div>
  <div class="col-sm-11">
    <h1 class="text-center">Create Guest</h1>
  </div>
</div>

<div class="row align-items-center mb-5 mt-5">
  <%= form_with model: @guest, url: admin_guests_path do |form| %>

    <div class="form-group">
      <%= form.label :name, "Guest Name" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :gender, "Guest Gender" %>

      <div class="form-check">
        <%= form.radio_button :gender, 0, class: "form-check-input" %>
        <%= form.label :gender, "Female", value: 1, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :gender, 1, class: "form-check-input" %>
        <%= form.label :gender, "Male", value: 0, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :contact, "Guest Contact" %>
      <%= form.text_field :contact, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :contact_source, "Guest Contact Source" %>
      <%= form.select :contact_source,
                      Guest::CONTACT_SOURCE.keys.map { |key| [Guest::CONTACT_SOURCE[key], key] },
                      { include_blank: "Select Source", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :from_groom, "Guest Relation" %>

      <div class="form-check">
        <%= form.radio_button :from_groom, true, class: "form-check-input" %>
        <%= form.label :from_groom, "Groom", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :from_groom, false, class: "form-check-input" %>
        <%= form.label :from_groom, "Bride", value: false, class: "form-check-label" %>
      </div>
    </div>
  </div>

    <div class="form-group">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>