config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/healthz' => 'health#index'
  get '/error' => 'error#index', as: 'error'

  # set redirector root to /invitations/books
  root to: redirect('/invitations/books')

  # modify devise path_names to avoid clash with existing
  devise_for :users, path: '_auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  namespace :admin, path: '_adminz' do

    # home controller, only display index and error. no resources
    get '/' => 'home#index', as: 'root'
    get '/error' => 'home#error', as: 'error'

    resources :venues
    resources :weddings
    resources :invitations
    resources :guests

    resources :users do
      patch '/confirm' => 'users#confirm', as: 'confirm'
      patch '/revoke' => 'users#revoke', as: 'revoke'
    end
  end

  namespace :invitations do
    scope :books do
      get '/' => 'books#index'
      get '/:id' => 'books#show', as: 'show'

      post '/:id' => 'books#create', as: 'create'
    end
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  self.table_name = "invitations"

  has_many :invitation_guests, class_name: 'InvitationGuest', foreign_key: :invitation_id
  has_many :guests, class_name: 'Guest', through: :invitation_guests

  belongs_to :wedding, class_name: 'Weddings'

  ATTENDANCE_TYPE = {
    "0".to_sym => 'Holy Matrimony',
    "1".to_sym => 'Reception',
    "2".to_sym => 'Both' # invited to both event
  }

  ATTENDANCE_TYPE_ENUM = {
    :holy_matrimony => 0,
    :reception => 1,
    :both => 2 # invited to both event
  }

  class << self
    def fetch_filled_comments(limit)
      self.where.not(comments: [nil, '']).limit(limit)
    end
  end

  def fetch_attendance_type
    ATTENDANCE_TYPE[self.attendance_type.to_s.to_sym]
  end

  def is_holy_matrimony_invited?
    self.attendance_type == 0
  end

  def is_reception_invited?
    self.attendance_type == 1
  end

  def is_both_events_invited?
    self.attendance_type == 2
  end

  def fetch_attending_info
    if self.attending.nil?
      "Not Confirmed"
    else
      self.attending ? "Attend" : "Not Attend"
    end
  end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < AdminController
  before_action :load_resource, only: [:edit, :update, :destroy]
  before_action :load_uninvited_guests, only: [:edit, :new]

  respond_to? :html
  layout 'admin'

  def index
    @invitations = InvitationService.retrieve(index_attributes)
  rescue StandardError => e
    log_error(e, action_name)
    session[:error_message] = e.message
    session[:error_backtrace] = e.backtrace.take(3)
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_error_url
  end

  def new
    @invitation = Invitation.new
  rescue StandardError => e
    log_error(e, action_name)
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_invitations_path
  end

  def create
    InvitationService.create(create_attributes)

    redirect_to admin_invitations_path, notice: 'Sukses menambah undangan'
  rescue InvitationService::InvitationError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:warning] = e.message
    redirect_to new_admin_invitation_path
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to new_admin_invitation_path
  end

  def edit
    selected_guests = @invitation.guests

    @guests = selected_guests + @guests
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_invitations_path
  end

  def update
    InvitationService.update(@invitation, update_attributes)

    redirect_to admin_invitations_path, notice: 'Sukses mengubah data undangan'
  rescue InvitationService::InvitationError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:warning] = e.message
    redirect_to edit_admin_invitation_path
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )

    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to edit_admin_invitation_path
  end

  def destroy
    InvitationService.delete(@invitation)

    redirect_to admin_invitations_path, notice: 'Sukses menghapus undangan'
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    flash[:error] = "Tetap tenang tetap semangat"
    redirect_to admin_invitations_path
  end

  private

  def load_resource
    @invitation = Invitation.find(params[:id])
  end

  def load_uninvited_guests
    uninvited_guests = Guest.left_outer_joins(:invitation_guests).where(invitation_guests: { guest_id: nil })

    @guests = uninvited_guests
  end

  def index_attributes
    attribute = params.permit(:search, :guest_source, :attendance_type, :commit).to_h

    # transform attributes
    attribute["search"] = attribute["search"].to_s.strip
    attribute["guest_source"] = attribute["guest_source"].to_s.strip
    attribute["attendance_type"] = attribute["attendance_type"].to_i if attribute["attendance_type"].present?

    attribute
  end

  def create_attributes
    attribute = params.required(:invitation)
          .permit(:wedding_id,
                  :participant,
                  :attendance_type,
                  :with_family,
                  :with_partner,
                  guest_ids: []
                ).to_h

    # transform attributes
    attribute[:wedding_id] = attribute[:wedding_id].to_i
    attribute[:guest_ids] = attribute[:guest_ids].map(&:to_i).reject { |x| x.zero? }
    attribute[:attendance_type] = attribute[:attendance_type].to_i
    attribute[:with_family] = (attribute[:with_family].to_s == "true") ? true : false
    attribute[:with_partner] = (attribute[:with_partner].to_s == "true") ? true : false
    attribute[:participant] = attribute[:guest_ids].count if attribute[:participant].to_i.zero?

    attribute
  end

  def update_attributes
    attribute = params.required(:invitation)
          .permit(:wedding_id,
                  :comments,
                  :participant,
                  :attendance_type,
                  :with_family,
                  :with_partner,
                  :sent,
                  guest_ids: []
                ).to_h

    # transform attributes
    attribute[:wedding_id] = attribute[:wedding_id].to_i
    attribute[:comments] = attribute[:comments].to_s
    attribute[:guest_ids] = attribute[:guest_ids].map(&:to_i).reject { |x| x.zero? }
    attribute[:attendance_type] = attribute[:attendance_type].to_i
    attribute[:with_family] = (attribute[:with_family].to_s == "true") ? true : false
    attribute[:with_partner] = (attribute[:with_partner].to_s == "true") ? true : false
    attribute[:sent] = (attribute[:sent].to_s == "true") ? true : false
    attribute[:participant] = attribute[:guest_ids].count if attribute[:participant].to_i.zero?

    attribute
  end
end

app/controllers/invitations/books_controller.rb
class Invitations::BooksController < ActionController::Base
  respond_to? :html
  before_action :load_resource, only: [:show, :create]

  MAX_DISPLAYED_COMMENTS = 25

  def index
    # pass required variables for erb templating
    @wedding = Weddings.first # hardcoded to display some information to the wedding
    @invtitaion_comments = Invitation.fetch_filled_comments(MAX_DISPLAYED_COMMENTS).shuffle
    @calendar_url = generate_calendar_url
  rescue StandardError => e
    log_error(e, action_name)
    redirect_to error_path
  end

  def show
    # pass required variables for erb templating
    @guests = generate_guests
    @wedding = @invitation.wedding
    @invtitaion_comments = Invitation.fetch_filled_comments(MAX_DISPLAYED_COMMENTS).shuffle
    @calendar_url = generate_calendar_url
  rescue StandardError => e
    log_error(e, action_name, params[:id])
    redirect_to error_path
  end

  def create
    BookService.book(@invitation, create_attributes)

    redirect_to invitations_show_path(@invitation)
  rescue StandardError => e
    Rails.logger.error(
      tags: ['controller', self.class.name, action_name],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        params: params,
      }
    )
    redirect_to error_path
  end

  private

  def load_resource
    @invitation = Invitation.find params[:id]
  rescue StandardError, ActiveRecord::RecordNotFound => e
    log_error(e, action_name, params[:id])
    redirect_to error_path
  end

  def create_attributes
    attribute = params.permit(:comments,
                              :attending).to_h

    # transform attributes
    attribute[:comments] = attribute[:comments].to_s.strip
    attribute[:attending] = (attribute[:attending].to_s == "yes") ? true : false

    attribute
  end

  def generate_guests
    guest = ""

    if @invitation.with_partner?
      guest = @invitation.guests.first.name + " & Partner"
    elsif @invitation.with_family?
      guest= @invitation.guests.first.name + " & Family"
    else
      guest = @invitation.guests.pluck(:name).join(" & ")
    end

    return guest
  end

  def generate_calendar_url
    calendar_hash = {
      text: "The Wedding Of Jhon Doe & Melissa",
      dates: "20270707T000000Z/20270707T030000Z",
      details: "You are invited to attend the holy matrimony of Jhon Doe & Melissa Wedding",
      location: "Big Valley Grace Community Church (https://maps.app.goo.gl/TaE5mthP91Df9gXF7)"
    }
    query_string = calendar_hash.to_query

    base_url = "https://calendar.google.com/calendar/r/eventedit?"
    return base_url + query_string
  end

  def log_error(e, action, track_id=0)
    Rails.logger.error(
      tags: ['controller', self.class.name, action],
      message: {
        message: e.message,
        stacktrace: e.backtrace.take(DEFAULT_BACKTRACE_LIMIT),
        track_id: track_id
      }
    )
  end
end

app/views/admin/invitations/edit.html.erb
<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-1">
    <a href=<%= admin_invitations_path %> class="no-style-link">
      <span>
        <i class="bx bx-left-arrow-alt"></i>
      </span>
      Back
    </a>
  </div>
  <div class="col-sm-11">
    <h1 class="text-center">Invitation Detail</h1>
  </div>
</div>

<div class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Wedding</th>
        <th>Guests</th>
        <th>Attending</th>
        <th>Comment</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          <td><%= @invitation.id %></td>
          <td><%= @invitation.wedding.hashtag %></td>
          <td><%= @invitation.guests&.pluck(:name)&.join(", ") %></td>
          <td><%= @invitation.fetch_attending_info%></td>
          <td><%= @invitation.comments %></td>
        </tr>
    </tbody>
  </table>
</div>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-12">
    <h1 class="text-center">Edit Form</h1>
  </div>
</div>

<div class="row align-items-center mb-5 mt-5">
  <%= form_with model: @invitation, url: admin_invitation_path(@invitation), method: :patch, local: true do |form| %>
    <div class="form-group">
      <%= form.label :wedding_id, "Select Wedding" %>
      <%= form.select :wedding_id,
                      Weddings.all.map { |wedding| [wedding.hashtag, wedding.id] },  # This will display the hashtag in the select box and submit the wedding.id
                      { include_blank: "Select Wedding", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :comments, "Invitation Comment" %>
      <%= form.text_area :comments, class: "form-control", rows: 3 %>
    </div>

    <div class="form-group">
      <%= form.label :attendance_type, "Attendance Type" %>
      <%= form.select :attendance_type,
                      Invitation::ATTENDANCE_TYPE.keys.map { |key| [Invitation::ATTENDANCE_TYPE[key], key] },
                      { include_blank: "Select Attendance Type", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :participant, "Participant" %>
      <%= form.number_field :participant, step: 1, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :with_family, "With Family?" %>

      <div class="form-check">
        <%= form.radio_button :with_family, true, checked: @invitation.with_family == true, class: "form-check-input" %>
        <%= form.label :with_family, "Yes", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :with_family, false, checked: @invitation.with_family == false, class: "form-check-input" %>
        <%= form.label :with_family, "No", value: false, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :with_partner, "With Partner?" %>

      <div class="form-check">
        <%= form.radio_button :with_partner, true, checked: @invitation.with_partner == true, class: "form-check-input" %>
        <%= form.label :with_partner, "Yes", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :with_partner, false, checked: @invitation.with_partner == false, class: "form-check-input" %>
        <%= form.label :with_partner, "No", value: false, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :sent, "Is Invitation Sent?" %>

      <div class="form-check">
        <%= form.radio_button :sent, true, checked: @invitation.sent == true, class: "form-check-input" %>
        <%= form.label :sent, "Yes", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :sent, false, checked: @invitation.sent == false, class: "form-check-input" %>
        <%= form.label :sent, "No", value: false, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :guest_ids, "Update Guests" %>
      <!-- Question mark icon with tooltip -->
      <span data-toggle="tooltip" data-placement="top" title="Select one or more guests to invite. Use Ctrl or Shift to select multiple.">
        <i class="bx bx-info-circle" style="font-size: 1.2em; cursor: pointer;"></i>
      </span>
    </div>

    <div class="form-group">
      <%= form.select :guest_ids, @guests.collect { |guest| [guest.name, guest.id] }, {}, { class: 'form-control select2', multiple: true, style: "width: 100%;" } %>
    </div>

    <div class="form-group text-center">
      <%= form.submit "Update", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/invitations/index.html.erb
<!-- app/views/admin/invitations/index.html.erb -->

<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-11">
    <h1 class="text-center">Invitations</h1>
  </div>
  <div class="col-sm-1">
    <%= link_to 'Add', new_admin_invitation_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th colspan="12" class="text-center">
          <%= form_tag admin_invitations_path, method: :get, class: 'form-inline d-flex justify-content-center' do %>
            <%= text_field_tag :search, params[:search], class: 'form-control mr-2', placeholder: "Search by guest", style: "width: 250px;" %>

            <%= select_tag :guest_source,
                options_for_select([['All', ''], ['Groom', 'groom'], ['Bride', 'bride']], params[:guest_source]),
                class: 'form-control mr-2',
                include_blank: false
            %>

            <%= select_tag :attendance_type,
                options_for_select([['All', '-1'], ['Holy Matrimony', '0'], ['Reception', '1'], ['Both', '2']], params[:attendance_type]),
                class: 'form-control mr-2',
                include_blank: false
            %>

            <%= submit_tag 'Search', class: 'btn btn-primary mr-2' %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>#</th>
        <th>ID</th>
        <th>Wedding</th>
        <th>Guests</th>
        <th>Family</th>
        <th>Partner</th>
        <th>Participant</th>
        <th>Attendance</th>
        <th>Attending</th>
        <th>Sent</th>
        <th>Comment</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @invitations&.each_with_index do |invitation, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to invitation.id, invitations_show_path(invitation) %></td>
          <td><%= invitation.wedding.hashtag %></td>
          <td><%= invitation.guests&.pluck(:name)&.join(", ") %></td>
          <td><%= invitation.with_family%></td>
          <td><%= invitation.with_partner%></td>
          <td><%= invitation.participant%></td>
          <td><%= invitation.fetch_attendance_type%></td>
          <td><%= invitation.fetch_attending_info%></td>
          <td><%= invitation.sent%></td>
          <td><%= invitation.comments %></td>
          <td>
            <%= link_to 'Edit', edit_admin_invitation_path(invitation), class: 'btn btn-primary' %>
            <%= link_to "Delete", admin_invitation_path(invitation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <button class="btn btn-success"
                onclick="generateAndCopy(this)"
                data-names="<%= j invitation.guests&.first&.name %>"
                data-path="<%= j invitations_show_path(invitation) %>"
                data-attendance-type="<%= j invitation.attendance_type %>">
              Generate Text
            </button>
          </td>
        </tr>
      <% end %>
      <tr>
        <<td colspan="12" class="text-center" style="font-weight: bold;">Total Participant: <%= @invitations.sum(&:participant) %></td>
      </tr>
    </tbody>
  </table>
</div>

<script>
  function generateAndCopy(button) {
    const names = button.getAttribute("data-names");
    const path = button.getAttribute("data-path");
    const host = window.location.origin;
    const attendance_type = button.getAttribute("data-attendance-type");

    let place = "";

    console.log(attendance_type)

    switch (attendance_type) {
      case "0":
        place = `💒 Holy Matrimony
Date: Saturday, July 7th, 2027
Time: 07:00 AM – 10:00 AM
Venue: Big Valley Grace Community Church`
        break;
      case "1":
place = `🍽️ Wedding Reception
Date: Saturday, July 7th, 2027
Time: 7:00 PM – 11:00 PM
Venue: Venice Boardwalk`
        break;
      case "2":
place = `💒 Holy Matrimony
Date: Saturday, July 7th, 2027
Time: 07:00 AM – 10:00 AM
Venue: Big Valley Grace Community Church

🍽️ Wedding Reception
Date: Saturday, July 7th, 2027
Time: 7:00 PM – 11:00 PM
Venue: Venice Boardwalk`
        break;
    }

    const text = `Dear Mr./Mrs./Ms. ${names},

With heartfelt joy, we invite you to join us in celebrating the union of:

Jhon Doe & Melissa

${place}

It would mean the world to us to have you witness and celebrate this special moment in our lives.
Whether in person or virtually, your presence is truly cherished.

To view our invitation and confirm your attendance, please visit the link below:

${host}${path}

We are deeply grateful for your support, blessings, and warm wishes as we embark on this new journey together.

With love and gratitude,
Jhon Doe & Melissa`;

    navigator.clipboard.writeText(text)
      .then(() => alert("Copied: " + text))
      .catch(err => alert("Failed to copy: " + err));
  }
</script>

app/views/admin/invitations/new.html.erb
<%= stylesheet_link_tag "admin" %>

<div class="row align-items-center mb-5 mt-5">
  <div class="col-sm-1">
    <a href=<%= admin_invitations_path %> class="no-style-link">
      <span>
        <i class="bx bx-left-arrow-alt"></i>
      </span>
      Back
    </a>
  </div>
  <div class="col-sm-11">
    <h1 class="text-center">Create Invitation</h1>
  </div>
</div>

<div class="row align-items-center mb-5 mt-5">
  <%= form_with model: @invitation, url: admin_invitations_path do |form| %>
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :wedding_id, "Select Wedding" %>
      <%= form.select :wedding_id,
                      Weddings.all.map { |wedding| [wedding.hashtag, wedding.id] },  # This will display the hashtag in the select box and submit the wedding.id
                      { include_blank: "Select Wedding", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :attendance_type, "Attendance Type" %>
      <%= form.select :attendance_type,
                      Invitation::ATTENDANCE_TYPE.keys.map { |key| [Invitation::ATTENDANCE_TYPE[key], key] },
                      { include_blank: "Select Attendance Type", required: true },
                      class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :participant, "Participant" %>
      <%= form.number_field :participant, step: 1, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :with_family, "With Family?" %>

      <div class="form-check">
        <%= form.radio_button :with_family, true, checked: @invitation.with_family == true, class: "form-check-input" %>
        <%= form.label :with_family, "Yes", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :with_family, false, checked: @invitation.with_family == false, class: "form-check-input" %>
        <%= form.label :with_family, "No", value: false, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :with_partner, "With Partner?" %>

      <div class="form-check">
        <%= form.radio_button :with_partner, true, checked: @invitation.with_partner == true, class: "form-check-input" %>
        <%= form.label :with_partner, "Yes", value: true, class: "form-check-label" %>
      </div>

      <div class="form-check">
        <%= form.radio_button :with_partner, false, checked: @invitation.with_partner == false, class: "form-check-input" %>
        <%= form.label :with_partner, "No", value: false, class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :guest_ids, "Add Guests" %>
      <!-- Question mark icon with tooltip -->
      <span data-toggle="tooltip" data-placement="top" title="Select one or more guests to invite.">
        <i class="bx bx-info-circle" style="font-size: 1.2em; cursor: pointer;"></i>
      </span>
    </div>

    <div class="form-group">
      <%= form.select :guest_ids, @guests.collect { |guest| [guest.name, guest.id] }, {}, { class: 'form-control select2', multiple: true, style: "width: 100%;" } %>
    </div>

    <div class="form-group">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>