config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/healthz' => 'health#index'
  get '/error' => 'error#index', as: 'error'

  # set redirector root to /invitations/books
  root to: redirect('/invitations/books')

  # modify devise path_names to avoid clash with existing
  devise_for :users, path: '_auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  namespace :admin, path: '_adminz' do

    # home controller, only display index and error. no resources
    get '/' => 'home#index', as: 'root'
    get '/error' => 'home#error', as: 'error'

    resources :venues
    resources :weddings
    resources :invitations
    resources :guests

    resources :users do
      patch '/confirm' => 'users#confirm', as: 'confirm'
      patch '/revoke' => 'users#revoke', as: 'revoke'
    end
  end

  namespace :invitations do
    scope :books do
      get '/' => 'books#index'
      get '/:id' => 'books#show', as: 'show'

      post '/:id' => 'books#create', as: 'create'
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="turbolinks-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Boxicons CSS -->
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
    <title>Admin page</title>

    <%= stylesheet_link_tag 'navbar', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <!-- navbar -->
        <nav class="navbar">
          <div class="logo_item">
            <%= link_to admin_root_url, class: 'logo_item', style: 'text-decoration: none; color: inherit;' do %>
            <i class="bx bx-menu" id="sidebarOpen"></i>
            <span class="">
              <i class="bx bx-sidebar"></i>
              Wedding Admin
            </span>
          <% end %>
          </div>
          <div class="text-center">
            <p>Welcome, <%= current_user.email %></p>
          </div>
          <div class="navbar_content">
            <i class="bi bi-grid"></i>
            <i class='bx bx-sun' id="darkLight"></i>
            <i class='bx bx-bell' ></i>
            <%# <img src="images/profile.jpg" alt="" class="profile" /> %>
          </div>
        </nav>
      </div>
      <div class="row">
          <div class="col-md-2">
            <!-- sidebar -->
            <nav class="sidebar">
              <div class="menu_content">
                <ul class="menu_items">
                  <div class="menu_title menu_dahsboard"></div>
                  <!-- duplicate or remove this li tag if you want to add or remove navlink with submenu -->
                  <!-- start -->
                  <li class="item">
                    <div class="nav_link submenu_item">
                      <span class="navlink_icon">
                        <i class="bx bx-cog"></i>
                      </span>
                      <span class="navlink">Configurations</span>
                      <i class="bx bx-chevron-right arrow-left"></i>
                    </div>
                    <ul class="menu_items submenu">
                      <a href=<%= admin_weddings_path %> class="nav_link sublink">
                        <span class="navlink_icon">
                          <i class="bx bx-bible"></i>
                        </span>
                        Weddings
                      </a>
                      <a href=<%= admin_venues_path %> class="nav_link sublink">
                        <span class="navlink_icon">
                          <i class="bx bx-building-house"></i>
                        </span>
                        Venues
                      </a>
                    </ul>
                  </li>
                  <!-- end -->
                  <!-- duplicate this li tag if you want to add or remove  navlink with submenu -->
                  <!-- start -->
                  <li class="item">
                    <div class="nav_link submenu_item">
                      <span class="navlink_icon">
                        <i class="bx bx-user-circle"></i>
                      </span>
                      <span class="navlink">Invitations</span>
                      <i class="bx bx-chevron-right arrow-left"></i>
                    </div>
                    <ul class="menu_items submenu">
                      <a href=<%= admin_invitations_path %> class="nav_link sublink">
                        <span class="navlink_icon">
                          <i class="bx bx-envelope"></i>
                        </span>
                        Invitations
                      </a>
                      <a href=<%= admin_guests_path %> class="nav_link sublink">
                        <span class="navlink_icon">
                          <i class="bx bxs-user-detail"></i>
                        </span>
                        Guests
                      </a>
                    </ul>
                  </li>
                  <!-- end -->
                  <!-- duplicate this li tag if you want to add or remove  navlink with submenu -->
                  <!-- start -->
                  <li class="item">
                    <div class="nav_link submenu_item">
                      <span class="navlink_icon">
                        <i class="bx bx-code-block"></i>
                      </span>
                      <span class="navlink">Administrator</span>
                      <i class="bx bx-chevron-right arrow-left"></i>
                    </div>
                    <ul class="menu_items submenu">
                      <a href=<%= admin_users_path %> class="nav_link sublink">
                        <span class="navlink_icon">
                          <i class="bx bxs-user-account"></i>
                        </span>
                        Accounts
                      </a>
                    </ul>
                  </li>
                  <!-- end -->
                </ul>
                <!-- Sidebar Open / Close -->
                <div class="bottom_content">
                  <div class="bottom expand_sidebar">
                    <span> Expand</span>
                    <i class='bx bx-log-in' ></i>
                  </div>
                    <div class="bottom collapse_sidebar">
                      <span> Collapse</span>
                      <%= link_to destroy_user_session_path, method: :delete, id: "logoutIcon", class: "logout-icon" do %>
                        <i class='bx bx-log-out'></i>
                      <% end %>
                    </div>
                </div>
              </div>
            </nav>
          </div>

          <div class="col-md-9">
              <!-- Admin reusable alert from server -->
              <% if flash[:error] %>
                <div class="alert alert-danger">
                  <%= flash[:error] %>
                </div>
              <% elsif flash[:warning] %>
                <div class="alert alert-warning">
                  <%= flash[:warning] %>
                </div>
              <% elsif flash[:notice] %>
                <div class="alert alert-success">
                  <%= flash[:notice] %>
                </div>
              <% end %>

              <!-- This is where the content will be injected -->
              <%= yield %>
          </div>
      </div>
    </div>
  </body>
</html>

<script>
const body = document.querySelector("body");
const darkLight = document.querySelector("#darkLight");
const sidebar = document.querySelector(".sidebar");
const submenuItems = document.querySelectorAll(".submenu_item");
const sidebarOpen = document.querySelector("#sidebarOpen");
const sidebarClose = document.querySelector(".collapse_sidebar");
const sidebarExpand = document.querySelector(".expand_sidebar");
sidebarOpen.addEventListener("click", () => sidebar.classList.toggle("close"));
sidebarClose.addEventListener("click", () => {
  sidebar.classList.add("close", "hoverable");
});
sidebarExpand.addEventListener("click", () => {
  sidebar.classList.remove("close", "hoverable");
});
sidebar.addEventListener("mouseenter", () => {
  if (sidebar.classList.contains("hoverable")) {
    sidebar.classList.remove("close");
  }
});
sidebar.addEventListener("mouseleave", () => {
  if (sidebar.classList.contains("hoverable")) {
    sidebar.classList.add("close");
  }
});
darkLight.addEventListener("click", () => {
  body.classList.toggle("dark");
  if (body.classList.contains("dark")) {
    document.setI
    darkLight.classList.replace("bx-sun", "bx-moon");
  } else {
    darkLight.classList.replace("bx-moon", "bx-sun");
  }
});
submenuItems.forEach((item, index) => {
  item.addEventListener("click", () => {
    item.classList.toggle("show_submenu");
    submenuItems.forEach((item2, index2) => {
      if (index !== index2) {
        item2.classList.remove("show_submenu");
      }
    });
  });
});
if (window.innerWidth < 768) {
  sidebar.classList.add("close");
} else {
  sidebar.classList.remove("close");
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <!-- Boxicons CSS -->
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>